In [30]:
import pandas as pd

In [31]:
data = pd.read_csv("C:/Users/DSi/Desktop/student data.csv")
print(data)

   ID   Name  Age  Salary      City
0  11   Yash   23   80000    Sangli
1  12  Rohan   33   70000  Kolhapur
2  13  Pooja   30   60000    Mumbai
3  14  Mansi   23   50000      Pune
4  15    Dev   20   40000  Banglore
5  13  Rashi   32   89000     Delhi

In [32]:
path = pd.read_excel("C:/Users/DSi/Desktop/Data Dictionary.xlsx")
print(path)

                    Variable  \
0                    SalesID
1                  MachineID
2                    ModelID
3                 datasource
4               auctioneerID
5                   YearMade
6   MachineHoursCurrentMeter
7                  UsageBand
8                   Saledate
9                  Saleprice
10               fiModelDesc
11               fiBaseModel
12           fiSecondaryDesc
13             fiModelSeries
14         fiModelDescriptor
15               ProductSize
16          ProductClassDesc
17                     State
18              ProductGroup
19          ProductGroupDesc
20              Drive_System
21                 Enclosure
22                     Forks
23                  Pad_Type
24              Ride_Control
25                     Stick
26              Transmission
27              Turbocharged
28           Blade_Extension
29               Blade_Width
30            Enclosure_Type
31         Engine_Horsepower
32                Hydraulics
33                 Pushblock
34                    Ripper
35                 Scarifier
36               Tip_control
37                 Tire_Size
38                   Coupler
39            Coupler_System
40            Grouser_Tracks
41           Hydraulics_Flow
42                Track_Type
43   Undercarriage_Pad_Width
44              Stick_Length
45                     Thumb
46           Pattern_Changer
47              Grouser_Type
48          Backhoe_Mounting
49                Blade_Type
50           Travel_Controls
51         Differential_Type
52         Steering_Controls

                                          Description  \
0     unique identifier of a particular sale of a ...
1     identifier for a particular machine;  machin...
2     identifier for a unique machine model (i.e. ...
3     source of the sale record;  some sources are...
4     identifier of a particular auctioneer, i.e. ...
5                 year of manufacturer of the Machine
6     current usage of the machine in hours at tim...
7     value (low, medium, high) calculated compari...
8                                        time of sale
9                                 cost of sale in USD
10    Description of a unique machine model (see M...
11                      disaggregation of fiModelDesc
12                      disaggregation of fiModelDesc
13                      disaggregation of fiModelDesc
14                      disaggregation of fiModelDesc
15                           Don't know what this is
16    description of 2nd level hierarchical groupi...
17                    US State in which sale occurred
18    identifier for top-level hierarchical groupi...
19    description of top-level hierarchical groupi...
20  machine configuration;  typcially describes wh...
21  machine configuration - does machine have an e...
22  machine configuration - attachment used for li...
23  machine configuration - type of treads a crawl...
24  machine configuration - optional feature on lo...
25           machine configuration - type of control
26  machine configuration - describes type of tran...
27  machine configuration - engine naturally aspir...
28  machine configuration - extension of standard ...
29             machine configuration - width of blade
30  machine configuration - does machine have an e...
31   machine configuration - engine horsepower rating
32         machine configuration - type of hydraulics
33                     machine configuration - option
34  machine configuration - implement attached to ...
35  machine configuration - implement attached to ...
36      machine configuration - type of blade control
37      machine configuration - size of primary tires
38  machine configuration - type of implement inte...
39  machine configuration - type of implement inte...
40  machine configuration - describes ground conta...
41  machine configuration - normal or high flow hy...
42  machine configuration - type of treads a crawl...
43    machine configuration - width of crawler treads
44  machine configuration - length of machine digg...
45  machine configuration - attachment used for gr...
46  machine configuration - can adjust the operato...
47  machine configuration - type of treads a crawl...
48  machine configuration - optional interface use...
49    machine configuration - describes type of blade
50  machine configuration - describes operator con...
51  machine configuration - differential type, typ...
52  machine configuration - describes operator con...

                                           Unnamed: 2
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15  The size class grouping for a product group. S...
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN
28                                                NaN
29                                                NaN
30                                                NaN
31                                                NaN
32                                                NaN
33                                                NaN
34                                                NaN
35                                                NaN
36                                                NaN
37                                                NaN
38                                                NaN
39                                                NaN
40                                                NaN
41                                                NaN
42                                                NaN
43                                                NaN
44                                                NaN
45                                                NaN
46                                                NaN
47                                                NaN
48                                                NaN
49                                                NaN
50                                                NaN
51                                                NaN
52                                                NaN

C:\Users\DSi\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:79: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

In [33]:
print(path.head())

       Variable                                        Description Unnamed: 2
0       SalesID    unique identifier of a particular sale of a ...        NaN
1     MachineID    identifier for a particular machine;  machin...        NaN
2       ModelID    identifier for a unique machine model (i.e. ...        NaN
3    datasource    source of the sale record;  some sources are...        NaN
4  auctioneerID    identifier of a particular auctioneer, i.e. ...        NaN

In [34]:
print(path.tail())

             Variable                                        Description  \
48   Backhoe_Mounting  machine configuration - optional interface use...
49         Blade_Type    machine configuration - describes type of blade
50    Travel_Controls  machine configuration - describes operator con...
51  Differential_Type  machine configuration - differential type, typ...
52  Steering_Controls  machine configuration - describes operator con...

   Unnamed: 2
48        NaN
49        NaN
50        NaN
51        NaN
52        NaN

In [35]:
print(path.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Variable     53 non-null     object
 1   Description  53 non-null     object
 2   Unnamed: 2   1 non-null      object
dtypes: object(3)
memory usage: 1.4+ KB
None

In [36]:
path.describe()

,Variable,Description,Unnamed: 2
count,53,53,1
unique,53,45,1
top,SalesID,disaggregation of fiModelDesc,The size class grouping for a product group. S...
freq,1,4,1

In [37]:
data.describe()

              ID        Age        Salary
count   6.000000   6.000000      6.000000
mean   13.000000  26.833333  64833.333333
std     1.414214   5.492419  18443.607745
min    11.000000  20.000000  40000.000000
25%    12.250000  23.000000  52500.000000
50%    13.000000  26.500000  65000.000000
75%    13.750000  31.500000  77500.000000
max    15.000000  33.000000  89000.000000

In [39]:
print(data.isnull())

      ID   Name    Age  Salary   City
0  False  False  False   False  False
1  False  False  False   False  False
2  False  False  False   False  False
3  False  False  False   False  False
4  False  False  False   False  False
5  False  False  False   False  False

In [19]:
print(path.isnull())

    Variable  Description  Unnamed: 2
0      False        False        True
1      False        False        True
2      False        False        True
3      False        False        True
4      False        False        True
5      False        False        True
6      False        False        True
7      False        False        True
8      False        False        True
9      False        False        True
10     False        False        True
11     False        False        True
12     False        False        True
13     False        False        True
14     False        False        True
15     False        False       False
16     False        False        True
17     False        False        True
18     False        False        True
19     False        False        True
20     False        False        True
21     False        False        True
22     False        False        True
23     False        False        True
24     False        False        True
25     False        False        True
26     False        False        True
27     False        False        True
28     False        False        True
29     False        False        True
30     False        False        True
31     False        False        True
32     False        False        True
33     False        False        True
34     False        False        True
35     False        False        True
36     False        False        True
37     False        False        True
38     False        False        True
39     False        False        True
40     False        False        True
41     False        False        True
42     False        False        True
43     False        False        True
44     False        False        True
45     False        False        True
46     False        False        True
47     False        False        True
48     False        False        True
49     False        False        True
50     False        False        True
51     False        False        True
52     False        False        True

In [40]:
print(path.isnull().sum())

Variable        0
Description     0
Unnamed: 2     52
dtype: int64

In [41]:
print(data.isnull().sum())

ID        0
Name      0
Age       0
Salary    0
City      0
dtype: int64

In [42]:
print(data['ID'].duplicated().sum())

1

In [44]:
print(data.drop_duplicates("ID"))

   ID   Name  Age  Salary      City
0  11   Yash   23   80000    Sangli
1  12  Rohan   33   70000  Kolhapur
2  13  Pooja   30   60000    Mumbai
3  14  Mansi   23   50000      Pune
4  15    Dev   20   40000  Banglore

In [45]:
# Working with Missing Data in Pandas
print(path)

                    Variable  \
0                    SalesID
1                  MachineID
2                    ModelID
3                 datasource
4               auctioneerID
5                   YearMade
6   MachineHoursCurrentMeter
7                  UsageBand
8                   Saledate
9                  Saleprice
10               fiModelDesc
11               fiBaseModel
12           fiSecondaryDesc
13             fiModelSeries
14         fiModelDescriptor
15               ProductSize
16          ProductClassDesc
17                     State
18              ProductGroup
19          ProductGroupDesc
20              Drive_System
21                 Enclosure
22                     Forks
23                  Pad_Type
24              Ride_Control
25                     Stick
26              Transmission
27              Turbocharged
28           Blade_Extension
29               Blade_Width
30            Enclosure_Type
31         Engine_Horsepower
32                Hydraulics
33                 Pushblock
34                    Ripper
35                 Scarifier
36               Tip_control
37                 Tire_Size
38                   Coupler
39            Coupler_System
40            Grouser_Tracks
41           Hydraulics_Flow
42                Track_Type
43   Undercarriage_Pad_Width
44              Stick_Length
45                     Thumb
46           Pattern_Changer
47              Grouser_Type
48          Backhoe_Mounting
49                Blade_Type
50           Travel_Controls
51         Differential_Type
52         Steering_Controls

                                          Description  \
0     unique identifier of a particular sale of a ...
1     identifier for a particular machine;  machin...
2     identifier for a unique machine model (i.e. ...
3     source of the sale record;  some sources are...
4     identifier of a particular auctioneer, i.e. ...
5                 year of manufacturer of the Machine
6     current usage of the machine in hours at tim...
7     value (low, medium, high) calculated compari...
8                                        time of sale
9                                 cost of sale in USD
10    Description of a unique machine model (see M...
11                      disaggregation of fiModelDesc
12                      disaggregation of fiModelDesc
13                      disaggregation of fiModelDesc
14                      disaggregation of fiModelDesc
15                           Don't know what this is
16    description of 2nd level hierarchical groupi...
17                    US State in which sale occurred
18    identifier for top-level hierarchical groupi...
19    description of top-level hierarchical groupi...
20  machine configuration;  typcially describes wh...
21  machine configuration - does machine have an e...
22  machine configuration - attachment used for li...
23  machine configuration - type of treads a crawl...
24  machine configuration - optional feature on lo...
25           machine configuration - type of control
26  machine configuration - describes type of tran...
27  machine configuration - engine naturally aspir...
28  machine configuration - extension of standard ...
29             machine configuration - width of blade
30  machine configuration - does machine have an e...
31   machine configuration - engine horsepower rating
32         machine configuration - type of hydraulics
33                     machine configuration - option
34  machine configuration - implement attached to ...
35  machine configuration - implement attached to ...
36      machine configuration - type of blade control
37      machine configuration - size of primary tires
38  machine configuration - type of implement inte...
39  machine configuration - type of implement inte...
40  machine configuration - describes ground conta...
41  machine configuration - normal or high flow hy...
42  machine configuration - type of treads a crawl...
43    machine configuration - width of crawler treads
44  machine configuration - length of machine digg...
45  machine configuration - attachment used for gr...
46  machine configuration - can adjust the operato...
47  machine configuration - type of treads a crawl...
48  machine configuration - optional interface use...
49    machine configuration - describes type of blade
50  machine configuration - describes operator con...
51  machine configuration - differential type, typ...
52  machine configuration - describes operator con...

                                           Unnamed: 2
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15  The size class grouping for a product group. S...
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20                                                NaN
21                                                NaN
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN
26                                                NaN
27                                                NaN
28                                                NaN
29                                                NaN
30                                                NaN
31                                                NaN
32                                                NaN
33                                                NaN
34                                                NaN
35                                                NaN
36                                                NaN
37                                                NaN
38                                                NaN
39                                                NaN
40                                                NaN
41                                                NaN
42                                                NaN
43                                                NaN
44                                                NaN
45                                                NaN
46                                                NaN
47                                                NaN
48                                                NaN
49                                                NaN
50                                                NaN
51                                                NaN
52                                                NaN

In [46]:
print(path.isnull())

    Variable  Description  Unnamed: 2
0      False        False        True
1      False        False        True
2      False        False        True
3      False        False        True
4      False        False        True
5      False        False        True
6      False        False        True
7      False        False        True
8      False        False        True
9      False        False        True
10     False        False        True
11     False        False        True
12     False        False        True
13     False        False        True
14     False        False        True
15     False        False       False
16     False        False        True
17     False        False        True
18     False        False        True
19     False        False        True
20     False        False        True
21     False        False        True
22     False        False        True
23     False        False        True
24     False        False        True
25     False        False        True
26     False        False        True
27     False        False        True
28     False        False        True
29     False        False        True
30     False        False        True
31     False        False        True
32     False        False        True
33     False        False        True
34     False        False        True
35     False        False        True
36     False        False        True
37     False        False        True
38     False        False        True
39     False        False        True
40     False        False        True
41     False        False        True
42     False        False        True
43     False        False        True
44     False        False        True
45     False        False        True
46     False        False        True
47     False        False        True
48     False        False        True
49     False        False        True
50     False        False        True
51     False        False        True
52     False        False        True

In [50]:
path1 = pd.read_csv("C:/Users/DSi/Desktop/WDICountry.csv")
print(path1)

    Country Code    Short Name    Table Name                     Long Name  \
0            ABW         Aruba         Aruba                         Aruba
1            AFG   Afghanistan   Afghanistan  Islamic State of Afghanistan
2            AGO        Angola        Angola   People's Republic of Angola
3            ALB       Albania       Albania           Republic of Albania
4            AND       Andorra       Andorra       Principality of Andorra
..           ...           ...           ...                           ...
258          XKX        Kosovo        Kosovo            Republic of Kosovo
259          YEM         Yemen   Yemen, Rep.             Republic of Yemen
260          ZAF  South Africa  South Africa      Republic of South Africa
261          ZMB        Zambia        Zambia            Republic of Zambia
262          ZWE      Zimbabwe      Zimbabwe          Republic of Zimbabwe

    2-alpha code       Currency Unit  \
0             AW       Aruban florin
1             AF      Afghan afghani
2             AO      Angolan kwanza
3             AL        Albanian lek
4             AD                Euro
..           ...                 ...
258           XK                Euro
259           YE         Yemeni rial
260           ZA  South African rand
261           ZM  New Zambian kwacha
262           ZW         U.S. dollar

                                         Special Notes  \
0    SNA data for 2000-2011 are updated from offici...
1    Fiscal year end: March 20; reporting period fo...
2                                                  NaN
3                                                  NaN
4    WB-3 code changed from ADO to AND to align wit...
..                                                 ...
258  WB-3 code changed from KSV to XKX to align wit...
259  Based on official government statistics and In...
260  Fiscal year end: March 31; reporting period fo...
261  The base year is 2010. National accounts data ...
262  Fiscal year end: June 30; reporting period for...

                         Region         Income Group WB-2 code  ...  \
0     Latin America & Caribbean          High income        AW  ...
1                    South Asia           Low income        AF  ...
2            Sub-Saharan Africa  Lower middle income        AO  ...
3         Europe & Central Asia  Upper middle income        AL  ...
4         Europe & Central Asia          High income        AD  ...
..                          ...                  ...       ...  ...
258       Europe & Central Asia  Lower middle income        XK  ...
259  Middle East & North Africa  Lower middle income        RY  ...
260          Sub-Saharan Africa  Upper middle income        ZA  ...
261          Sub-Saharan Africa  Lower middle income        ZM  ...
262          Sub-Saharan Africa           Low income        ZW  ...

                       IMF data dissemination standard  \
0                                                  NaN
1    Enhanced General Data Dissemination System (e-...
2    Enhanced General Data Dissemination System (e-...
3    Enhanced General Data Dissemination System (e-...
4                                                  NaN
..                                                 ...
258  Enhanced General Data Dissemination System (e-...
259  Enhanced General Data Dissemination System (e-...
260         Special Data Dissemination Standard (SDDS)
261  Enhanced General Data Dissemination System (e-...
262  Enhanced General Data Dissemination System (e-...

                              Latest population census  \
0                                                 2010
1                                                 1979
2                                                 2014
3                                                 2011
4    2011. Population data compiled from administra...
..                                                 ...
258                                               2011
259                                               2004
260                                               2011
261                                               2010
262                                               2012

                               Latest household survey  \
0                                                  NaN
1                  Demographic and Health Survey, 2015
2               Demographic and Health Survey, 2015/16
3               Demographic and Health Survey, 2008/09
4                                                  NaN
..                                                 ...
258         Multiple Indicator Cluster Survey, 2013/14
259                Demographic and Health Survey, 2013
260  Demographic and Health Survey, 2003; World Hea...
261             Demographic and Health Survey, 2013/14
262                Demographic and Health Survey, 2015

     Source of most recent Income and expenditure data  \
0                                                  NaN
1              Integrated household survey (IHS), 2011
2           Integrated household survey (IHS), 2008/09
3    Living Standards Measurement Study Survey (LSM...
4                                                  NaN
..                                                 ...
258     Expenditure survey/budget survey (ES/BS), 2013
259     Expenditure survey/budget survey (ES/BS), 2005
260  Expenditure survey/budget survey (ES/BS), 2010/11
261            Integrated household survey (IHS), 2010
262         Integrated household survey (IHS), 2011/12

    Vital registration complete Latest agricultural census  \
0                           Yes                        NaN
1                           NaN                        NaN
2                           NaN                        NaN
3                           Yes                       2012
4                           Yes                        NaN
..                          ...                        ...
258                         NaN                       2014
259                         NaN                        NaN
260                         NaN                       2007
261                         NaN                        NaN
262                         NaN                        NaN

    Latest industrial data Latest trade data Latest water withdrawal data  \
0                      NaN            2015.0                          NaN
1                      NaN            2015.0                       2000.0
2                      NaN            2015.0                       2005.0
3                   2013.0            2015.0                       2006.0
4                      NaN            2014.0                          NaN
..                     ...               ...                          ...
258                    NaN               NaN                          NaN
259                 2012.0            2015.0                       2005.0
260                 2010.0            2016.0                       2013.0
261                    NaN            2015.0                       2002.0
262                    NaN            2015.0                       2007.0

    Unnamed: 31
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
..          ...
258         NaN
259         NaN
260         NaN
261         NaN
262         NaN

[263 rows x 32 columns]

In [51]:
print(path1.isnull().sum())

Country Code                                           0
Short Name                                             0
Table Name                                             0
Long Name                                              0
2-alpha code                                           2
Currency Unit                                         46
Special Notes                                        113
Region                                                46
Income Group                                          46
WB-2 code                                              1
National accounts base year                           58
National accounts reference year                     209
SNA price valuation                                   62
Lending category                                     120
Other groups                                         204
System of National Accounts                           48
Alternative conversion factor                        216
PPP survey year                                       72
Balance of Payments Manual in use                     60
External debt Reporting status                       140
System of trade                                       61
Government Accounting concept                         99
IMF data dissemination standard                       80
Latest population census                              46
Latest household survey                              111
Source of most recent Income and expenditure data     98
Vital registration complete                          148
Latest agricultural census                           131
Latest industrial data                               146
Latest trade data                                     70
Latest water withdrawal data                          82
Unnamed: 31                                          263
dtype: int64

In [52]:
print(path1.dropna())

Empty DataFrame
Columns: [Country Code, Short Name, Table Name, Long Name, 2-alpha code, Currency Unit, Special Notes, Region, Income Group, WB-2 code, National accounts base year, National accounts reference year, SNA price valuation, Lending category, Other groups, System of National Accounts, Alternative conversion factor, PPP survey year, Balance of Payments Manual in use, External debt Reporting status, System of trade, Government Accounting concept, IMF data dissemination standard, Latest population census, Latest household survey, Source of most recent Income and expenditure data, Vital registration complete, Latest agricultural census, Latest industrial data, Latest trade data, Latest water withdrawal data, Unnamed: 31]
Index: []

[0 rows x 32 columns]

In [55]:
import numpy as np
print(path1.replace(np.nan,"Hi"))

    Country Code    Short Name    Table Name                     Long Name  \
0            ABW         Aruba         Aruba                         Aruba
1            AFG   Afghanistan   Afghanistan  Islamic State of Afghanistan
2            AGO        Angola        Angola   People's Republic of Angola
3            ALB       Albania       Albania           Republic of Albania
4            AND       Andorra       Andorra       Principality of Andorra
..           ...           ...           ...                           ...
258          XKX        Kosovo        Kosovo            Republic of Kosovo
259          YEM         Yemen   Yemen, Rep.             Republic of Yemen
260          ZAF  South Africa  South Africa      Republic of South Africa
261          ZMB        Zambia        Zambia            Republic of Zambia
262          ZWE      Zimbabwe      Zimbabwe          Republic of Zimbabwe

    2-alpha code       Currency Unit  \
0             AW       Aruban florin
1             AF      Afghan afghani
2             AO      Angolan kwanza
3             AL        Albanian lek
4             AD                Euro
..           ...                 ...
258           XK                Euro
259           YE         Yemeni rial
260           ZA  South African rand
261           ZM  New Zambian kwacha
262           ZW         U.S. dollar

                                         Special Notes  \
0    SNA data for 2000-2011 are updated from offici...
1    Fiscal year end: March 20; reporting period fo...
2                                                   Hi
3                                                   Hi
4    WB-3 code changed from ADO to AND to align wit...
..                                                 ...
258  WB-3 code changed from KSV to XKX to align wit...
259  Based on official government statistics and In...
260  Fiscal year end: March 31; reporting period fo...
261  The base year is 2010. National accounts data ...
262  Fiscal year end: June 30; reporting period for...

                         Region         Income Group WB-2 code  ...  \
0     Latin America & Caribbean          High income        AW  ...
1                    South Asia           Low income        AF  ...
2            Sub-Saharan Africa  Lower middle income        AO  ...
3         Europe & Central Asia  Upper middle income        AL  ...
4         Europe & Central Asia          High income        AD  ...
..                          ...                  ...       ...  ...
258       Europe & Central Asia  Lower middle income        XK  ...
259  Middle East & North Africa  Lower middle income        RY  ...
260          Sub-Saharan Africa  Upper middle income        ZA  ...
261          Sub-Saharan Africa  Lower middle income        ZM  ...
262          Sub-Saharan Africa           Low income        ZW  ...

                       IMF data dissemination standard  \
0                                                   Hi
1    Enhanced General Data Dissemination System (e-...
2    Enhanced General Data Dissemination System (e-...
3    Enhanced General Data Dissemination System (e-...
4                                                   Hi
..                                                 ...
258  Enhanced General Data Dissemination System (e-...
259  Enhanced General Data Dissemination System (e-...
260         Special Data Dissemination Standard (SDDS)
261  Enhanced General Data Dissemination System (e-...
262  Enhanced General Data Dissemination System (e-...

                              Latest population census  \
0                                                 2010
1                                                 1979
2                                                 2014
3                                                 2011
4    2011. Population data compiled from administra...
..                                                 ...
258                                               2011
259                                               2004
260                                               2011
261                                               2010
262                                               2012

                               Latest household survey  \
0                                                   Hi
1                  Demographic and Health Survey, 2015
2               Demographic and Health Survey, 2015/16
3               Demographic and Health Survey, 2008/09
4                                                   Hi
..                                                 ...
258         Multiple Indicator Cluster Survey, 2013/14
259                Demographic and Health Survey, 2013
260  Demographic and Health Survey, 2003; World Hea...
261             Demographic and Health Survey, 2013/14
262                Demographic and Health Survey, 2015

     Source of most recent Income and expenditure data  \
0                                                   Hi
1              Integrated household survey (IHS), 2011
2           Integrated household survey (IHS), 2008/09
3    Living Standards Measurement Study Survey (LSM...
4                                                   Hi
..                                                 ...
258     Expenditure survey/budget survey (ES/BS), 2013
259     Expenditure survey/budget survey (ES/BS), 2005
260  Expenditure survey/budget survey (ES/BS), 2010/11
261            Integrated household survey (IHS), 2010
262         Integrated household survey (IHS), 2011/12

    Vital registration complete Latest agricultural census  \
0                           Yes                         Hi
1                            Hi                         Hi
2                            Hi                         Hi
3                           Yes                       2012
4                           Yes                         Hi
..                          ...                        ...
258                          Hi                       2014
259                          Hi                         Hi
260                          Hi                       2007
261                          Hi                         Hi
262                          Hi                         Hi

    Latest industrial data Latest trade data Latest water withdrawal data  \
0                       Hi            2015.0                           Hi
1                       Hi            2015.0                       2000.0
2                       Hi            2015.0                       2005.0
3                   2013.0            2015.0                       2006.0
4                       Hi            2014.0                           Hi
..                     ...               ...                          ...
258                     Hi                Hi                           Hi
259                 2012.0            2015.0                       2005.0
260                 2010.0            2016.0                       2013.0
261                     Hi            2015.0                       2002.0
262                     Hi            2015.0                       2007.0

    Unnamed: 31
0            Hi
1            Hi
2            Hi
3            Hi
4            Hi
..          ...
258          Hi
259          Hi
260          Hi
261          Hi
262          Hi

[263 rows x 32 columns]

In [56]:
print(path1)

    Country Code    Short Name    Table Name                     Long Name  \
0            ABW         Aruba         Aruba                         Aruba
1            AFG   Afghanistan   Afghanistan  Islamic State of Afghanistan
2            AGO        Angola        Angola   People's Republic of Angola
3            ALB       Albania       Albania           Republic of Albania
4            AND       Andorra       Andorra       Principality of Andorra
..           ...           ...           ...                           ...
258          XKX        Kosovo        Kosovo            Republic of Kosovo
259          YEM         Yemen   Yemen, Rep.             Republic of Yemen
260          ZAF  South Africa  South Africa      Republic of South Africa
261          ZMB        Zambia        Zambia            Republic of Zambia
262          ZWE      Zimbabwe      Zimbabwe          Republic of Zimbabwe

    2-alpha code       Currency Unit  \
0             AW       Aruban florin
1             AF      Afghan afghani
2             AO      Angolan kwanza
3             AL        Albanian lek
4             AD                Euro
..           ...                 ...
258           XK                Euro
259           YE         Yemeni rial
260           ZA  South African rand
261           ZM  New Zambian kwacha
262           ZW         U.S. dollar

                                         Special Notes  \
0    SNA data for 2000-2011 are updated from offici...
1    Fiscal year end: March 20; reporting period fo...
2                                                  NaN
3                                                  NaN
4    WB-3 code changed from ADO to AND to align wit...
..                                                 ...
258  WB-3 code changed from KSV to XKX to align wit...
259  Based on official government statistics and In...
260  Fiscal year end: March 31; reporting period fo...
261  The base year is 2010. National accounts data ...
262  Fiscal year end: June 30; reporting period for...

                         Region         Income Group WB-2 code  ...  \
0     Latin America & Caribbean          High income        AW  ...
1                    South Asia           Low income        AF  ...
2            Sub-Saharan Africa  Lower middle income        AO  ...
3         Europe & Central Asia  Upper middle income        AL  ...
4         Europe & Central Asia          High income        AD  ...
..                          ...                  ...       ...  ...
258       Europe & Central Asia  Lower middle income        XK  ...
259  Middle East & North Africa  Lower middle income        RY  ...
260          Sub-Saharan Africa  Upper middle income        ZA  ...
261          Sub-Saharan Africa  Lower middle income        ZM  ...
262          Sub-Saharan Africa           Low income        ZW  ...

                       IMF data dissemination standard  \
0                                                  NaN
1    Enhanced General Data Dissemination System (e-...
2    Enhanced General Data Dissemination System (e-...
3    Enhanced General Data Dissemination System (e-...
4                                                  NaN
..                                                 ...
258  Enhanced General Data Dissemination System (e-...
259  Enhanced General Data Dissemination System (e-...
260         Special Data Dissemination Standard (SDDS)
261  Enhanced General Data Dissemination System (e-...
262  Enhanced General Data Dissemination System (e-...

                              Latest population census  \
0                                                 2010
1                                                 1979
2                                                 2014
3                                                 2011
4    2011. Population data compiled from administra...
..                                                 ...
258                                               2011
259                                               2004
260                                               2011
261                                               2010
262                                               2012

                               Latest household survey  \
0                                                  NaN
1                  Demographic and Health Survey, 2015
2               Demographic and Health Survey, 2015/16
3               Demographic and Health Survey, 2008/09
4                                                  NaN
..                                                 ...
258         Multiple Indicator Cluster Survey, 2013/14
259                Demographic and Health Survey, 2013
260  Demographic and Health Survey, 2003; World Hea...
261             Demographic and Health Survey, 2013/14
262                Demographic and Health Survey, 2015

     Source of most recent Income and expenditure data  \
0                                                  NaN
1              Integrated household survey (IHS), 2011
2           Integrated household survey (IHS), 2008/09
3    Living Standards Measurement Study Survey (LSM...
4                                                  NaN
..                                                 ...
258     Expenditure survey/budget survey (ES/BS), 2013
259     Expenditure survey/budget survey (ES/BS), 2005
260  Expenditure survey/budget survey (ES/BS), 2010/11
261            Integrated household survey (IHS), 2010
262         Integrated household survey (IHS), 2011/12

    Vital registration complete Latest agricultural census  \
0                           Yes                        NaN
1                           NaN                        NaN
2                           NaN                        NaN
3                           Yes                       2012
4                           Yes                        NaN
..                          ...                        ...
258                         NaN                       2014
259                         NaN                        NaN
260                         NaN                       2007
261                         NaN                        NaN
262                         NaN                        NaN

    Latest industrial data Latest trade data Latest water withdrawal data  \
0                      NaN            2015.0                          NaN
1                      NaN            2015.0                       2000.0
2                      NaN            2015.0                       2005.0
3                   2013.0            2015.0                       2006.0
4                      NaN            2014.0                          NaN
..                     ...               ...                          ...
258                    NaN               NaN                          NaN
259                 2012.0            2015.0                       2005.0
260                 2010.0            2016.0                       2013.0
261                    NaN            2015.0                       2002.0
262                    NaN            2015.0                       2007.0

    Unnamed: 31
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
..          ...
258         NaN
259         NaN
260         NaN
261         NaN
262         NaN

[263 rows x 32 columns]

In [57]:
path1["National accounts reference year"] = path1["National accounts reference year"].replace(np.nan, 2005)
print(path1)

    Country Code    Short Name    Table Name                     Long Name  \
0            ABW         Aruba         Aruba                         Aruba
1            AFG   Afghanistan   Afghanistan  Islamic State of Afghanistan
2            AGO        Angola        Angola   People's Republic of Angola
3            ALB       Albania       Albania           Republic of Albania
4            AND       Andorra       Andorra       Principality of Andorra
..           ...           ...           ...                           ...
258          XKX        Kosovo        Kosovo            Republic of Kosovo
259          YEM         Yemen   Yemen, Rep.             Republic of Yemen
260          ZAF  South Africa  South Africa      Republic of South Africa
261          ZMB        Zambia        Zambia            Republic of Zambia
262          ZWE      Zimbabwe      Zimbabwe          Republic of Zimbabwe

    2-alpha code       Currency Unit  \
0             AW       Aruban florin
1             AF      Afghan afghani
2             AO      Angolan kwanza
3             AL        Albanian lek
4             AD                Euro
..           ...                 ...
258           XK                Euro
259           YE         Yemeni rial
260           ZA  South African rand
261           ZM  New Zambian kwacha
262           ZW         U.S. dollar

                                         Special Notes  \
0    SNA data for 2000-2011 are updated from offici...
1    Fiscal year end: March 20; reporting period fo...
2                                                  NaN
3                                                  NaN
4    WB-3 code changed from ADO to AND to align wit...
..                                                 ...
258  WB-3 code changed from KSV to XKX to align wit...
259  Based on official government statistics and In...
260  Fiscal year end: March 31; reporting period fo...
261  The base year is 2010. National accounts data ...
262  Fiscal year end: June 30; reporting period for...

                         Region         Income Group WB-2 code  ...  \
0     Latin America & Caribbean          High income        AW  ...
1                    South Asia           Low income        AF  ...
2            Sub-Saharan Africa  Lower middle income        AO  ...
3         Europe & Central Asia  Upper middle income        AL  ...
4         Europe & Central Asia          High income        AD  ...
..                          ...                  ...       ...  ...
258       Europe & Central Asia  Lower middle income        XK  ...
259  Middle East & North Africa  Lower middle income        RY  ...
260          Sub-Saharan Africa  Upper middle income        ZA  ...
261          Sub-Saharan Africa  Lower middle income        ZM  ...
262          Sub-Saharan Africa           Low income        ZW  ...

                       IMF data dissemination standard  \
0                                                  NaN
1    Enhanced General Data Dissemination System (e-...
2    Enhanced General Data Dissemination System (e-...
3    Enhanced General Data Dissemination System (e-...
4                                                  NaN
..                                                 ...
258  Enhanced General Data Dissemination System (e-...
259  Enhanced General Data Dissemination System (e-...
260         Special Data Dissemination Standard (SDDS)
261  Enhanced General Data Dissemination System (e-...
262  Enhanced General Data Dissemination System (e-...

                              Latest population census  \
0                                                 2010
1                                                 1979
2                                                 2014
3                                                 2011
4    2011. Population data compiled from administra...
..                                                 ...
258                                               2011
259                                               2004
260                                               2011
261                                               2010
262                                               2012

                               Latest household survey  \
0                                                  NaN
1                  Demographic and Health Survey, 2015
2               Demographic and Health Survey, 2015/16
3               Demographic and Health Survey, 2008/09
4                                                  NaN
..                                                 ...
258         Multiple Indicator Cluster Survey, 2013/14
259                Demographic and Health Survey, 2013
260  Demographic and Health Survey, 2003; World Hea...
261             Demographic and Health Survey, 2013/14
262                Demographic and Health Survey, 2015

     Source of most recent Income and expenditure data  \
0                                                  NaN
1              Integrated household survey (IHS), 2011
2           Integrated household survey (IHS), 2008/09
3    Living Standards Measurement Study Survey (LSM...
4                                                  NaN
..                                                 ...
258     Expenditure survey/budget survey (ES/BS), 2013
259     Expenditure survey/budget survey (ES/BS), 2005
260  Expenditure survey/budget survey (ES/BS), 2010/11
261            Integrated household survey (IHS), 2010
262         Integrated household survey (IHS), 2011/12

    Vital registration complete Latest agricultural census  \
0                           Yes                        NaN
1                           NaN                        NaN
2                           NaN                        NaN
3                           Yes                       2012
4                           Yes                        NaN
..                          ...                        ...
258                         NaN                       2014
259                         NaN                        NaN
260                         NaN                       2007
261                         NaN                        NaN
262                         NaN                        NaN

    Latest industrial data Latest trade data Latest water withdrawal data  \
0                      NaN            2015.0                          NaN
1                      NaN            2015.0                       2000.0
2                      NaN            2015.0                       2005.0
3                   2013.0            2015.0                       2006.0
4                      NaN            2014.0                          NaN
..                     ...               ...                          ...
258                    NaN               NaN                          NaN
259                 2012.0            2015.0                       2005.0
260                 2010.0            2016.0                       2013.0
261                    NaN            2015.0                       2002.0
262                    NaN            2015.0                       2007.0

    Unnamed: 31
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
..          ...
258         NaN
259         NaN
260         NaN
261         NaN
262         NaN

[263 rows x 32 columns]

In [58]:
print(path1.head(10))

  Country Code            Short Name            Table Name  \
0          ABW                 Aruba                 Aruba
1          AFG           Afghanistan           Afghanistan
2          AGO                Angola                Angola
3          ALB               Albania               Albania
4          AND               Andorra               Andorra
5          ARB            Arab World            Arab World
6          ARE  United Arab Emirates  United Arab Emirates
7          ARG             Argentina             Argentina
8          ARM               Armenia               Armenia
9          ASM        American Samoa        American Samoa

                      Long Name 2-alpha code   Currency Unit  \
0                         Aruba           AW   Aruban florin
1  Islamic State of Afghanistan           AF  Afghan afghani
2   People's Republic of Angola           AO  Angolan kwanza
3           Republic of Albania           AL    Albanian lek
4       Principality of Andorra           AD            Euro
5                    Arab World           1A             NaN
6          United Arab Emirates           AE   U.A.E. dirham
7            Argentine Republic           AR  Argentine peso
8           Republic of Armenia           AM   Armenian dram
9                American Samoa           AS     U.S. dollar

                                       Special Notes  \
0  SNA data for 2000-2011 are updated from offici...
1  Fiscal year end: March 20; reporting period fo...
2                                                NaN
3                                                NaN
4  WB-3 code changed from ADO to AND to align wit...
5  Arab World aggregate. Arab World is composed o...
6                                                NaN
7  National Institute of Statistics and Census re...
8                                                NaN
9                                                NaN

                       Region         Income Group WB-2 code  ...  \
0   Latin America & Caribbean          High income        AW  ...
1                  South Asia           Low income        AF  ...
2          Sub-Saharan Africa  Lower middle income        AO  ...
3       Europe & Central Asia  Upper middle income        AL  ...
4       Europe & Central Asia          High income        AD  ...
5                         NaN                  NaN        1A  ...
6  Middle East & North Africa          High income        AE  ...
7   Latin America & Caribbean  Upper middle income        AR  ...
8       Europe & Central Asia  Lower middle income        AM  ...
9         East Asia & Pacific  Upper middle income        AS  ...

                     IMF data dissemination standard  \
0                                                NaN
1  Enhanced General Data Dissemination System (e-...
2  Enhanced General Data Dissemination System (e-...
3  Enhanced General Data Dissemination System (e-...
4                                                NaN
5                                                NaN
6  Enhanced General Data Dissemination System (e-...
7         Special Data Dissemination Standard (SDDS)
8         Special Data Dissemination Standard (SDDS)
9                                                NaN

                            Latest population census  \
0                                               2010
1                                               1979
2                                               2014
3                                               2011
4  2011. Population data compiled from administra...
5                                                NaN
6                                               2010
7                                               2010
8                                               2011
9                                               2010

                      Latest household survey  \
0                                         NaN
1         Demographic and Health Survey, 2015
2      Demographic and Health Survey, 2015/16
3      Demographic and Health Survey, 2008/09
4                                         NaN
5                                         NaN
6                   World Health Survey, 2003
7  Multiple Indicator Cluster Survey, 2011/12
8      Demographic and Health Survey, 2015/16
9                                         NaN

   Source of most recent Income and expenditure data  \
0                                                NaN
1            Integrated household survey (IHS), 2011
2         Integrated household survey (IHS), 2008/09
3  Living Standards Measurement Study Survey (LSM...
4                                                NaN
5                                                NaN
6                                                NaN
7            Integrated household survey (IHS), 2014
8            Integrated household survey (IHS), 2014
9                                                NaN

  Vital registration complete Latest agricultural census  \
0                         Yes                        NaN
1                         NaN                        NaN
2                         NaN                        NaN
3                         Yes                       2012
4                         Yes                        NaN
5                         NaN                        NaN
6                         NaN                       2012
7                         Yes                       2008
8                         Yes                       2014
9                         Yes                       2008

  Latest industrial data Latest trade data Latest water withdrawal data  \
0                    NaN            2015.0                          NaN
1                    NaN            2015.0                       2000.0
2                    NaN            2015.0                       2005.0
3                 2013.0            2015.0                       2006.0
4                    NaN            2014.0                          NaN
5                    NaN               NaN                          NaN
6                    NaN            2015.0                       2005.0
7                 2002.0            2015.0                       2011.0
8                    NaN            2015.0                       2012.0
9                    NaN               NaN                          NaN

  Unnamed: 31
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
5         NaN
6         NaN
7         NaN
8         NaN
9         NaN

[10 rows x 32 columns]

In [65]:
# Column Transformations In Pandas (Part1) = 
path2 = pd.read_csv("C:/Users/DSi/Desktop/student_data_A.csv")
print(path2)

   Roll No First Name  Last Name   Address Class   Physics  Chemistry  Maths  \
0      101     Akshay      Patil      Pune   HSC        76         73     69
1      102       Amol     Patole      Pune   HSC        86         82     90
2      103     Ankita      Patil    Sangli   HSC        87         93     95
3      104       Yash   Chougule    Sangli   HSC        92         93     94
4      105     Ganesh    Samdole      Pune   HSC        78         73     81
5      106      Omkar      Sutar    Mumbai   HSC        85         75     66
6      107   Priyanka  Deshpande    Mumbai   HSC        91         90     94
7      108     Sachin     Magdum    Satara   HSC        83         67     70
8      109     Sakshi    Parmane  Kolhapur   HSC        80         86     84
9      110     Sanjay   Kulkarni    Mumbai   HSC        93         94     96

   Biology  English  Total Marks  Total Marks Obtained  Percentage
0       79       85          500                   371        74.2
1       80       84          500                   422        84.4
2       88       90          500                   453        90.6
3       96       95          500                   470        94.0
4       78       84          500                   394        78.8
5       76       82          500                   384        76.8
6       89       95          500                   459        91.8
7       73       79          500                   372        74.4
8       74       80          500                   404        80.8
9       90       95          500                   468        93.6

In [64]:
path2.loc[(path2["Percentage"] == 35), "Result"] = "Pass"
path2.loc[(path2["Percentage"] > 50), "Result"] = "Third Class"
path2.loc[(path2["Percentage"] > 65), "Result"] = "Second Class"
path2.loc[(path2["Percentage"] > 75), "Result"] = "First Class"
path2.loc[(path2["Percentage"] > 85), "Result"] = "Distinction"
print(path2)

   Roll No      Name Address Class   Physics  Chemistry  Maths  Biology  \
0      101    Akshay    Pune   HSC        76         73     69       79
1      102      Amol    Pune   HSC        86         82     90       80
2      103    Ankita  Sangli   HSC        87         93     95       88
3      104      Yash  Sangli   HSC        92         93     94       96
4      105    Ganesh    Pune   HSC        78         73     81       78
5      106     Omkar  Mumbai   HSC        85         75     66       76
6      107  Priyanka  Mumbai   HSC        91         90     94       89
7      108    Sachin  Satara   HSC        83         67     70       73
8      109    Sakshi  Satara   HSC        80         86     84       74
9      110    Sanjay  Mumbai   HSC        93         94     96       90

   English  Total Marks  Total Marks Obtained  Percentage        Result
0       85          500                   371        74.2  Second Class
1       84          500                   422        84.4   First Class
2       90          500                   453        90.6   Distinction
3       95          500                   470        94.0   Distinction
4       84          500                   394        78.8   First Class
5       82          500                   384        76.8   First Class
6       95          500                   459        91.8   Distinction
7       79          500                   372        74.4  Second Class
8       80          500                   404        80.8   First Class
9       95          500                   468        93.6   Distinction

In [68]:
path2["Full Name"] = path2["First Name"] +" "+ path2["Last Name"]
print(path2)

   Roll No First Name  Last Name   Address Class   Physics  Chemistry  Maths  \
0      101     Akshay      Patil      Pune   HSC        76         73     69
1      102       Amol     Patole      Pune   HSC        86         82     90
2      103     Ankita      Patil    Sangli   HSC        87         93     95
3      104       Yash   Chougule    Sangli   HSC        92         93     94
4      105     Ganesh    Samdole      Pune   HSC        78         73     81
5      106      Omkar      Sutar    Mumbai   HSC        85         75     66
6      107   Priyanka  Deshpande    Mumbai   HSC        91         90     94
7      108     Sachin     Magdum    Satara   HSC        83         67     70
8      109     Sakshi    Parmane  Kolhapur   HSC        80         86     84
9      110     Sanjay   Kulkarni    Mumbai   HSC        93         94     96

   Biology  English  Total Marks  Total Marks Obtained  Percentage  \
0       79       85          500                   371        74.2
1       80       84          500                   422        84.4
2       88       90          500                   453        90.6
3       96       95          500                   470        94.0
4       78       84          500                   394        78.8
5       76       82          500                   384        76.8
6       89       95          500                   459        91.8
7       73       79          500                   372        74.4
8       74       80          500                   404        80.8
9       90       95          500                   468        93.6

            Full Name
0        Akshay Patil
1         Amol Patole
2        Ankita Patil
3       Yash Chougule
4      Ganesh Samdole
5         Omkar Sutar
6  Priyanka Deshpande
7       Sachin Magdum
8      Sakshi Parmane
9     Sanjay Kulkarni